plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

loom {
	accessWidenerPath = file("src/main/resources/redbits.accesswidener")
	runtimeOnlyLog4j = true
}

repositories {

	// Cloth Config
	maven {
		url "https://maven.shedaniel.me/"
	}

	// ModMenu
	maven {
		url 'https://maven.terraformersmc.com'
	}

	// Modrinth
	maven {
		url = "https://api.modrinth.com/maven"
	}

	// Vazkii mods
//	maven {
//		url 'https://maven.blamejared.com'
//	}

}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}" transitive false

	// ModMenu
	implementation "com.terraformersmc:modmenu:${project.modmenu_version}" transitive false

	// Fabric API
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	// Cloth Config
	include( implementation("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_version}") ) exclude group: 'net.fabricmc.fabric-api'

	// Patchouli
	implementation "maven.modrinth:nU0bVIaL:AveV4Tjn"

}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand (
				"version": project.version
		)
	}
}

java {
	toolchain {
		languageVersion.set(JavaLanguageVersion.of(25))
	}
}
