# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_version = 2.5.1
maven_group = net.darktree
archives_base_name = redbits

minecraft_version=26.3-snapshot-10
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Dependencies
fabric_api_version=0.158.3+26.3
modmenu_version=21.0.0-alpha.1
#patchouli_version=26.1-94